DIFFERENT_SENDER: str = "Different sender"
WRONG_RECEIVER: str = "Wrong receiver"
UNAUTHORIZED: str = "Unauthorized"
ALREADY_OPTED_IN: str = "Already opted in"
WORSE_BID: str = "Worse bid"
SALE_ALREADY_EXISTS: str = "Sale already exists"
