DIFFERENT_SENDER: str = "Different sender"
WRONG_RECEIVER: str = "Wrong receiver"
UNAUTHORIZED: str = "Unauthorized"
ALREADY_OPTED_IN: str = "Already opted in"
BALANCE_NOT_EMPTY: str = "Balance not empty"
